In [1]:
import pandas as pd
import numpy as np

In [2]:
loan_applications = pd.read_csv("loan_applications.csv")

In [3]:
borrower_profiles = pd.read_csv("borrower_profiles.csv")

In [4]:
loan_applications.shape

(601, 12)

In [9]:
borrower_profiles.shape

(500, 11)

In [5]:
loan_applications.index

RangeIndex(start=0, stop=601, step=1)

In [6]:
borrower_profiles.index

RangeIndex(start=0, stop=500, step=1)

In [12]:
borrower_profiles.columns

Index(['borrower_id', 'age', 'state', 'education_level', 'employment_status',
       'years_employed', 'annual_income', 'credit_score', 'home_ownership',
       'dependents', 'existing_monthly_debt'],
      dtype='str')

In [7]:
loan_applications.columns

Index(['loan_id', 'borrower_id', 'application_date', 'loan_purpose',
       'loan_amount', 'term_months', 'interest_rate', 'monthly_payment',
       'dti_ratio', 'loan_status', 'days_delinquent', 'defaulted'],
      dtype='str')

In [13]:
loan_applications.head(10)

,loan_id,borrower_id,application_date,loan_purpose,loan_amount,term_months,interest_rate,monthly_payment,dti_ratio,loan_status,days_delinquent,defaulted
0,LN-00001,BRW-0001,2024-01-08,Vacation,16100.0,36,13.05,542.86,55.5,Paid Off,0,0
1,LN-00002,BRW-0001,2024-08-13,Major Purchase,5600.0,48,14.21,153.62,40.4,Default,138,1
2,LN-00003,BRW-0002,2025-06-28,Moving,44700.0,36,12.37,1492.59,70.5,Paid Off,0,0
3,LN-00004,BRW-0003,2025-05-18,Auto Loan,9200.0,48,11.18,238.58,59.8,Default,34,1
4,LN-00005,BRW-0004,2025-03-24,Moving,11200.0,36,9.66,359.61,44.1,Current,0,0
5,LN-00006,BRW-0005,2025-04-19,Education,28600.0,48,13.07,768.26,37.1,Current,0,0
6,LN-00007,BRW-0006,2024-07-04,Medical Expenses,39200.0,12,10.23,3450.50,49.9,Paid Off,0,0
7,LN-00008,BRW-0007,2025-03-29,Home Improvement,36300.0,48,14.26,996.69,38.2,Default,38,1
8,LN-00009,BRW-0007,2024-08-01,Business Loan,39000.0,60,13.73,902.01,36.8,Current,0,0
9,LN-00010,BRW-0008,2024-11-01,Debt Consolidation,28400.0,12,11.88,2521.71,67.8,Default,43,1

In [8]:
borrower_profiles.head(5)

,borrower_id,age,state,education_level,employment_status,years_employed,annual_income,credit_score,home_ownership,dependents,existing_monthly_debt
0,BRW-0001,62,CT,High School,Self-Employed,6,31020,596,Rent,1,892
1,BRW-0002,24,CO,High School,Full-Time,4,40188,543,Own,2,869
2,BRW-0003,50,NC,Bachelor,Contract,22,41014,611,Mortgage,0,1806
3,BRW-0004,43,TX,High School,Full-Time,19,35036,701,Mortgage,2,928
4,BRW-0005,46,NY,High School,Full-Time,18,44528,715,Own,0,608

In [9]:
loan_applications.info()

<class 'pandas.DataFrame'>
RangeIndex: 601 entries, 0 to 600
Data columns (total 12 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   loan_id           601 non-null    str
 1   borrower_id       601 non-null    str
 2   application_date  601 non-null    str
 3   loan_purpose      601 non-null    str
 4   loan_amount       601 non-null    float64
 5   term_months       601 non-null    int64
 6   interest_rate     601 non-null    float64
 7   monthly_payment   601 non-null    float64
 8   dti_ratio         601 non-null    float64
 9   loan_status       601 non-null    str
 10  days_delinquent   601 non-null    int64
 11  defaulted         601 non-null    int64
dtypes: float64(4), int64(3), str(5)
memory usage: 82.5 KB

In [10]:
borrower_profiles.info()

<class 'pandas.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 11 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   borrower_id            500 non-null    str
 1   age                    500 non-null    int64
 2   state                  500 non-null    str
 3   education_level        500 non-null    str
 4   employment_status      500 non-null    str
 5   years_employed         500 non-null    int64
 6   annual_income          500 non-null    int64
 7   credit_score           500 non-null    int64
 8   home_ownership         500 non-null    str
 9   dependents             500 non-null    int64
 10  existing_monthly_debt  500 non-null    int64
dtypes: int64(6), str(5)
memory usage: 59.3 KB

In [15]:
loan_applications.describe()

,loan_amount,term_months,interest_rate,monthly_payment,dti_ratio,days_delinquent,defaulted
count,601.000000,601.000000,601.000000,601.000000,601.000000,601.000000,601.000000
mean,22148.252912,36.539101,10.641331,948.337654,49.680699,27.036606,0.242928
std,13215.261422,16.898192,2.251153,864.959543,24.113652,47.802845,0.429209
min,2000.000000,12.000000,5.860000,44.140000,7.600000,0.000000,0.000000
25%,10900.000000,24.000000,8.940000,359.860000,32.200000,0.000000,0.000000
50%,20400.000000,36.000000,10.540000,684.870000,48.100000,0.000000,0.000000
75%,32700.000000,48.000000,12.330000,1165.200000,62.400000,30.000000,0.000000
max,49800.000000,60.000000,15.860000,4262.690000,177.400000,180.000000,1.000000

In [17]:
borrower_profiles.describe()

,age,years_employed,annual_income,credit_score,dependents,existing_monthly_debt
count,500.000000,500.000000,500.000000,500.000000,500.000000,500.000000
mean,44.986000,10.854000,64471.484000,704.952000,1.356000,1585.166000
std,13.539736,9.301706,28959.837645,97.339157,1.252358,1089.979915
min,22.000000,0.000000,12549.000000,528.000000,0.000000,124.000000
25%,33.000000,3.000000,42968.250000,617.750000,0.000000,788.750000
50%,45.000000,8.000000,59282.500000,708.000000,1.000000,1312.000000
75%,57.000000,17.000000,79780.500000,794.250000,2.000000,2131.750000
max,68.000000,35.000000,157047.000000,850.000000,4.000000,6130.000000

In [11]:
loan_applications["defaulted"].nunique()

2

## What is the overall default rate

In [17]:
default_customers = loan_applications["defaulted"].sum()

In [23]:
default_customers

np.int64(146)

In [30]:
total_count = loan_applications["defaulted"].count()

In [31]:
total_count

np.int64(601)

In [18]:
loan_applications.tail(5)

,loan_id,borrower_id,application_date,loan_purpose,loan_amount,term_months,interest_rate,monthly_payment,dti_ratio,loan_status,days_delinquent,defaulted
596,LN-00597,BRW-0497,2025-02-06,Wedding,29100.0,36,7.38,903.59,52.3,Default,31,1
597,LN-00598,BRW-0498,2024-04-19,Moving,4600.0,12,7.27,398.60,32.4,Current,0,0
598,LN-00599,BRW-0499,2024-02-24,Education,7800.0,60,9.86,165.19,28.8,Current,0,0
599,LN-00600,BRW-0500,2024-11-14,Medical Expenses,26400.0,24,11.44,1235.85,73.2,Late,15,0
600,LN-00601,BRW-0500,2024-05-03,Wedding,7500.0,12,10.70,661.81,62.9,Current,0,0

In [36]:
loan_default_rate = (default_customers / total_count) * 100

In [37]:
loan_default_rate

np.float64(24.292845257903494)

In [43]:
borrower_profiles

,borrower_id,age,state,education_level,employment_status,years_employed,annual_income,credit_score,home_ownership,dependents,existing_monthly_debt,credit_band
0,BRW-0001,62,CT,High School,Self-Employed,6,31020,596,Rent,1,892,520-599
1,BRW-0002,24,CO,High School,Full-Time,4,40188,543,Own,2,869,520-599
2,BRW-0003,50,NC,Bachelor,Contract,22,41014,611,Mortgage,0,1806,600-649
3,BRW-0004,43,TX,High School,Full-Time,19,35036,701,Mortgage,2,928,700-749
4,BRW-0005,46,NY,High School,Full-Time,18,44528,715,Own,0,608,700-749
...,...,...,...,...,...,...,...,...,...,...,...,...
495,BRW-0496,27,IL,Bachelor,Contract,4,60337,661,Mortgage,0,2359,650-699
496,BRW-0497,23,MO,High School,Full-Time,3,54617,773,Rent,3,1475,750+
497,BRW-0498,30,CO,Doctorate,Self-Employed,7,85000,845,Mortgage,3,1894,750+
498,BRW-0499,62,MA,Bachelor,Full-Time,14,62749,811,Rent,1,1339,750+
499,BRW-0500,31,MO,Associate,Full-Time,5,67070,604,Mortgage,0,2856,600-649

In [19]:
bins = [520, 600, 650, 700, 750, np.inf]
labels = ['520-599', '600-649', '650-699', '700-749', '750+']

borrower_profiles['credit_band'] = pd.cut(borrower_profiles['credit_score'], bins=bins, labels=labels, right=False)

In [27]:
bins = [0, 21, 41, 61, 81, np.inf]
labels = ['0-20.99', '21-40.99', '41-60.99', '61-80.99', '81+']

loan_applications['dti_band'] = pd.cut(loan_applications['dti_ratio'], bins=bins, labels=labels, right=False)

In [31]:
bins = [18, 31, 44, 57, np.inf]
labels = ['18-30', '31-43', '44-56', '57+']

borrower_profiles['age_group'] = pd.cut(borrower_profiles['age'], bins=bins, labels=labels, right=False)

In [37]:
bins = [5, 8, 11, 14, np.inf]
labels = ['5-7.99', '8-10.99', '11-13.99', '14+']

loan_applications['interest_rate'].rename = 'interest_rate_band'

In [33]:
print(loan_applications['interest_rate'].dtype)

category

In [34]:
loan_applications

,loan_id,borrower_id,application_date,loan_purpose,loan_amount,term_months,interest_rate,monthly_payment,dti_ratio,loan_status,days_delinquent,defaulted,dti_band
0,LN-00001,BRW-0001,2024-01-08,Vacation,16100.0,36,11-13.99,542.86,55.5,Paid Off,0,0,41-60.99
1,LN-00002,BRW-0001,2024-08-13,Major Purchase,5600.0,48,14+,153.62,40.4,Default,138,1,21-40.99
2,LN-00003,BRW-0002,2025-06-28,Moving,44700.0,36,11-13.99,1492.59,70.5,Paid Off,0,0,61-80.99
3,LN-00004,BRW-0003,2025-05-18,Auto Loan,9200.0,48,11-13.99,238.58,59.8,Default,34,1,41-60.99
4,LN-00005,BRW-0004,2025-03-24,Moving,11200.0,36,8-10.99,359.61,44.1,Current,0,0,41-60.99
...,...,...,...,...,...,...,...,...,...,...,...,...,...
596,LN-00597,BRW-0497,2025-02-06,Wedding,29100.0,36,5-7.99,903.59,52.3,Default,31,1,41-60.99
597,LN-00598,BRW-0498,2024-04-19,Moving,4600.0,12,5-7.99,398.60,32.4,Current,0,0,21-40.99
598,LN-00599,BRW-0499,2024-02-24,Education,7800.0,60,8-10.99,165.19,28.8,Current,0,0,21-40.99
599,LN-00600,BRW-0500,2024-11-14,Medical Expenses,26400.0,24,11-13.99,1235.85,73.2,Late,15,0,61-80.99
600,LN-00601,BRW-0500,2024-05-03,Wedding,7500.0,12,8-10.99,661.81,62.9,Current,0,0,61-80.99

In [35]:
borrower_profiles

,borrower_id,age,state,education_level,employment_status,years_employed,annual_income,credit_score,home_ownership,dependents,existing_monthly_debt,credit_band,age_group
0,BRW-0001,62,CT,High School,Self-Employed,6,31020,596,Rent,1,892,520-599,57+
1,BRW-0002,24,CO,High School,Full-Time,4,40188,543,Own,2,869,520-599,18-30
2,BRW-0003,50,NC,Bachelor,Contract,22,41014,611,Mortgage,0,1806,600-649,44-56
3,BRW-0004,43,TX,High School,Full-Time,19,35036,701,Mortgage,2,928,700-749,31-43
4,BRW-0005,46,NY,High School,Full-Time,18,44528,715,Own,0,608,700-749,44-56
...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,BRW-0496,27,IL,Bachelor,Contract,4,60337,661,Mortgage,0,2359,650-699,18-30
496,BRW-0497,23,MO,High School,Full-Time,3,54617,773,Rent,3,1475,750+,18-30
497,BRW-0498,30,CO,Doctorate,Self-Employed,7,85000,845,Mortgage,3,1894,750+,18-30
498,BRW-0499,62,MA,Bachelor,Full-Time,14,62749,811,Rent,1,1339,750+,57+
499,BRW-0500,31,MO,Associate,Full-Time,5,67070,604,Mortgage,0,2856,600-649,31-43

In [38]:
from sqlalchemy import create_engine
import urllib.parse

connection_string = urllib.parse.quote_plus(
    'DRIVER={ODBC Driver 17 for SQL Server};'
    'SERVER=AyoDAnalyst\\SQLEXPRESS01;'
    'DATABASE=LoanDB;'
    'Trusted_Connection=yes;'
)

engine = create_engine(
    f'mssql+pyodbc:///?odbc_connect={connection_string}'
)

In [39]:
borrower_profiles.to_sql(
    'borrower_profiles',
    engine,
    schema='dbo',
    if_exists='replace',
    index=False
)

loan_applications.to_sql(
    'loan_applications',
    engine,
    schema='dbo',
    if_exists='replace',
    index=False
)

118